### ISSUE TITLE
[Feat] 리스트에서 아이템 클릭시 띄울 정보 창 생성

### ISSUE THREAD

**Issue by commitcomplete** [commitcomplete/Cafe#6]
### 문제 상황
- 리스트의 아이템 클릭시 카페의 정보를 띄울 창이 필요하다. 
- 웹뷰 혹은 커스텀 창을 제공하여 해당 카페에 대한 정보들을 보여준다.

### TODO
- [ ] ~~webview를 제공하여 카페에 대한 정보를 네이버 지도에서 클릭했을때 처럼 보여준다.~~
- [ ] ~~커스텀 뷰를 만들어 해당 좌표값에 있는 상점에 대한 정보를 받아 커스텀하여 처리해준다.~~
- [ ] URL Scheme을 이용한 네이버 지도 연동 ( 기존의 방법들은 지원하지 않는 것들로 확인)
